### ISSUE TITLE
irr todo items

### ISSUE THREAD

**Issue by jarrodmillman** [statlab/permute#12]
- [ ] split by attribute
- [ ] split by video
- [ ] sparse -> full
- [ ] combination method? (NPC, n^{-1/2} weighting, something else)
